sudo: false
language: node_js
node_js:
  - '10'

notifications:
  email: false

script:
  - npm run copy-static
  - firebase --project PROJECT_NAME --token FIREBASE_TOKEN
  - psi --strategy mobile https://tewst-landing-page.firebaseapp.com
