sudo: false
language: node_js
node_js:
  - '9'

notifications:
  email: false

cache:
  bundler: true
  directories:
  - node_modules

script:
  - npm run test
  - npm run default
  - npm run deploy

after_success:
  - npm run pagespeed
  - exit 0
