sudo: false
language: node_js
node_js:
  - '5'

notifications:
  email: false

cache:
  bundler: true
  directories:
  - node_modules

before_script:
  - npm install -g gulp
  - npm install

script:
  - gulp default
  - gulp deploy

after_success:
  - exit 0