sudo: false
language: node_js
node_js:
  - '6'

notifications:
  email: false

cache:
  bundler: true
  directories:
  - node_modules

script:
  - npm run test
  - npm run default
  - npm run deploy

after_script:
  - npm run pagespeed

after_success:
  - exit 0
