sudo: false
language: node_js
node_js:
  - '10'

notifications:
  email: false

before_install:
  - mkdir www/ && mkdir www/assets/

script:
  - npm run minify
  - npm run copy
  - npm run deploy
  - npm run pagespeed
