sudo: false
language: node_js
node_js:
  - '10'

notifications:
  email: false

before_install:
  - mkdir www/ && mkdir www/assets/

script:
  - npm run build
  - npm run test
  - npm run deploy
  - npm run pagespeed
