sudo: false
language: node_js
node_js:
  - '12'

notifications:
  email: false

before_install:
  - mkdir www/ && mkdir www/assets/

script:
  - npm install dialogflow firebase-functions firebase-admin firebase-functions-test
  - npm run build
  - npm run deploy

# after_script:
#   - npm run pagespeed
